### ISSUE TITLE
GLSL 4.00 required

### ISSUE THREAD

**Issue by icanrealizeum** [OsnaCS/plantex#199]
```rust
...
INFO:client::game: Free GPU memory (estimated): 507MB
WARN:client::game_context: failed to compile program 'plants':
Compilation error in one of the shaders: 0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES\n")', src/libcore/result.rs:783
stack backtrace:
   1:     0x5607b2818763 - std::sys::backtrace::tracing::imp::write::hd6ff14ec50f4c192
   2:     0x5607b281cfcd - std::panicking::default_hook::{{closure}}::hd0a31e7ddfe371ae
   3:     0x5607b281beda - std::panicking::default_hook::hce63b9617bf0dd48
   4:     0x5607b281c4d8 - std::panicking::rust_panic_with_hook::hc9b5281dab10f831
   5:     0x5607b281c372 - std::panicking::begin_panic::h413368f2a185bb58
   6:     0x5607b281c2b0 - std::panicking::begin_panic_fmt::h07a69fe36d46d71b
   7:     0x5607b281c231 - rust_begin_unwind
   8:     0x5607b286c68f - core::panicking::panic_fmt::h43cb0a82d31d1236
   9:     0x5607b21973d5 - core::result::unwrap_failed::h6c1ecb656747c0ac
                        at /home/z/build/1nonpkgs/rust/rust/src/libcore/macros.rs:29
  10:     0x5607b216de83 - <core::result::Result<T, E>>::unwrap::hf34bc3308b823248
                        at /home/z/build/1nonpkgs/rust/rust/src/libcore/result.rs:721
  11:     0x5607b22aeab4 - client::view::plant_renderer::PlantRenderer::new::h85e278a30402e985
                        at /tmp/plantex/client/src/view/plant_renderer.rs:20
  12:     0x5607b22a4f1e - client::world::world_view::WorldView::new::h1c699d00c72aea8b
                        at /tmp/plantex/client/src/world/world_view.rs:37
  13:     0x5607b22a7fe1 - client::world_manager::WorldManager::new::h0a46b3db402a872b
                        at /tmp/plantex/client/src/world_manager.rs:39
  14:     0x5607b2283bf2 - client::game::Game::new::hb3a15e6c171eb875
                        at /tmp/plantex/client/src/game.rs:46
  15:     0x5607b22b67a2 - client::start_game::h6160f04476527f22
                        at /tmp/plantex/client/src/lib.rs:46
  16:     0x5607b20f5276 - plantex::main::h9ec5feb6dac7c282
                        at /tmp/plantex/plantex/main.rs:32
  17:     0x5607b2824cd6 - __rust_maybe_catch_panic
  18:     0x5607b281b751 - std::rt::lang_start::h0e8fe7c0c6be4cdb
  19:     0x5607b20f5563 - main
  20:     0x7f655f406290 - __libc_start_main
  21:     0x5607b20ec959 - _start
  22:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/plantex` (exit code: 101)

```

**Comment by LukasKalbertodt** [comment]
This is intended, as we are using the tesselation feature by default. Try to launch the game like this to disable the feature:

```bash
cargo run --bin plantex --release -- --tessellation=off
```
